### ISSUE TITLE
New Documentations for this API

### ISSUE THREAD

**Issue by piyush97** [piyush97/Slika-API#19]
Need to make Documentations for this API.
Either using Normal HTML or Use any Documentation Library.

**Comment by phoenix1796** [comment]
Would swagger UI work?

**Comment by piyush97** [comment]
@phoenix1796 	
Sure!

**Comment by piyush97** [comment]
Is there any progress? @phoenix1796

**Comment by 97amarnathk** [comment]
Can I be assigned this?

**Comment by phoenix1796** [comment]
Hi, apologies for the delayed response, I've mapped out the basic API endpoints and am in the middle of mapping them down.

**Comment by piyush97** [comment]
Sure

Regards
Piyush Mehta
http://piyushmehta.com
https://github.com/piyush97
https://linkedin.com/in/piyush24

**Comment by piyush97** [comment]
The earlier the better

Regards
Piyush Mehta
http://piyushmehta.com
https://github.com/piyush97
https://linkedin.com/in/piyush24
