### ISSUE TITLE
Add Test Cases using Mocha or Jest

### ISSUE THREAD

**Issue by piyush97** [piyush97/Slika-API#20]
Add Test Cases using Mocha or Jest for this API server

**Comment by helloart3mis** [comment]
I'd like to try this :)

**Comment by piyush97** [comment]
Sure, go for it

Regards
Piyush Mehta
https://piyushmehta.com
https://github.com/piyush97
https://linkedin.com/in/piyush24

**Comment by mathiasdonoso** [comment]
I want to help with this!

**Comment by piyush97** [comment]
> I want to help with this!

Sure! Just go for it!

**Comment by gustafsilva** [comment]
It I can try do? :smiley:

**Comment by mathiasdonoso** [comment]
> It I can try do? 😃

I can do a pr with the code I worked, that way you can see the test suite that I propose and we can work in different test

**Comment by mathiasdonoso** [comment]
> > I want to help with this!
> 
> Sure! Just go for it!

There will be a staging branch? (as the Pull Request Template says).

**Comment by piyush97** [comment]
> > > I want to help with this!
> > 
> > 
> > Sure! Just go for it!
> 
> Just one question....There will be a staging branch? (as the Pull Request Template says).
> 
> Greetings

https://github.com/piyush97/Slika-API/tree/staging
Here it is!

**Comment by piyush97** [comment]
> > It I can try do? 😃
> 
> I can do a pr with the code I worked, that way you can see the test suite that I propose and we can work in different test

Do send us a PR!

**Comment by piyush97** [comment]
I've merged it, although it's causing issues, I'm looking into it

**Comment by mathiasdonoso** [comment]
> I've merged it, although it's causing issues, I'm looking into it

Mmmm I think it is because package.json and package-lock.json are not syncronized.... my bad... I didn't commit package-lock.json

I can make another pr fixing this

**Comment by piyush97** [comment]
Sure.

Regards
Piyush Mehta
https://piyushmehta.com
https://github.com/piyush97
https://linkedin.com/in/piyush24

**Comment by piyush97** [comment]
Merged!

**Comment by piyush97** [comment]
@mathiasdonoso Can you work on the profile page too?

**Comment by piyush97** [comment]
@mathiasdonoso 	NPM run test is still failing.

**Comment by mathiasdonoso** [comment]
> @mathiasdonoso NPM run test is still failing.

Are this tests failing locally? I saw then running well on Travis, can you give more information to fix this?
